version: '3.3'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:latest
    ports:
    - "3000:3000"
    - "5000:5000"
    networks:
    - tyk
    volumes:
    - "./confs/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf"
    environment:
    - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE}
    depends_on:
    - tyk-redis
    - tyk-mongo
  tyk-gateway:
    image: tykio/tyk-gateway:latest
    ports:
    - "8080:8080"
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-dashboard
    volumes:
    - "./certs:/opt/tyk-gateway/certs"
    - "./confs/tyk.conf:/opt/tyk-gateway/tyk.conf"
  tyk-gateway-http:
    image: tykio/tyk-gateway:latest
    ports:
    - "8083:8080"
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-dashboard
    environment:
    - TYK_GW_HTTPSERVEROPTIONS_USESSL=false
    volumes:
    - "./certs:/opt/tyk-gateway/certs"
    - "./confs/tyk.conf:/opt/tyk-gateway/tyk.conf"
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:latest
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-mongo
    volumes:
    - "./confs/pump.conf:/opt/tyk-pump/pump.conf"
  tyk-redis:
    image: redis
    volumes:
    - redis-data:/data
    networks:
    - tyk
  tyk-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    volumes:
    - mongo-data:/data/db
    networks:
    - tyk
  tyk-grpc-go-plugin-server:
    image: davidgarvey/tyk-grpc-go-plugin-scratch
    networks:
        - tyk
  tyk-mdcb:
    image: tykio/tyk-mdcb-docker:latest
    networks:
      - tyk
    environment:
      - TYK_MDCB_LICENSE=${MDCB_LICENCE}
    volumes:
      - "./confs/tyk_sink.conf:/opt/tyk-sink/tyk_sink.conf"
  tyk-gateway-edge:
    image: tykio/tyk-gateway:latest
    ports:
    - "8081:8080"
    networks:
    - tyk
    depends_on:
    - tyk-redis-edge
    - tyk-mdcb
    volumes:
    - "./certs:/opt/tyk-gateway/certs"
    - "./confs/tyk-edge.conf:/opt/tyk-gateway/tyk.conf"
  tyk-redis-edge:
    image: redis
    volumes:
    - redis-edge-data:/data
    networks:
    - tyk
  httpbin:
    image: kennethreitz/httpbin
    networks:
    - tyk
    ports:
      - 8082:80
  tyk-identity-broker:
    image: tykio/tyk-identity-broker:latest
    networks:
      - tyk
    ports:
      - 3010:3010
    environment:
      - REDIGOCLUSTER_SHARDCOUNT=256
      - SESSION_SECRET=12345
    volumes:
      - "./confs/tib.conf:/opt/tyk-identity-broker/tib.conf"
      - "./confs/profiles.json:/opt/tyk-identity-broker/profiles.json"

volumes:
  redis-data:
  redis-edge-data:
  mongo-data:

networks:
  tyk:
